#!/usr/bin/env php
<?php
require_once('bootstrap.php');
require_once('bulldoc/output_generator.php');
require_once('bulldoc/chm_generator.php');


class docgenBuilder extends bookLoader
{
  
//---------------------------------------------------
  private function buildBook($key)
  {
    if (!isset($this->books[$key])) {
      $this->createBook($key);
      echo 'New book created';
    } else {
      $generator= new outputGenerator($this->getBook($key));
      $generator->build();
    }
  }
//---------------------------------------------------
  private function createBook($key)
  {
    $bookDir=colesoApplication::getConfigVal('/bulldoc/source')."$key/";
    mkdir ($bookDir,0777);
    mkdir ($bookDir.'pages',0777);
    file_put_contents($bookDir.'toc.yml','');
    file_put_contents($bookDir.'book_data.yml',"title: $key\nauthor: Incognito\ncopyright: Me, 2008\nsite: www.mysite.ru");
    
    $bookshelfFile=colesoApplication::getConfigVal('/bulldoc/bookshelfConfig');
    file_put_contents($bookshelfFile,"\n$key:",FILE_APPEND);
  }
//---------------------------------------------------
  public function run()
  {
    global $argc,$argv;
    if ($argc < 2 || in_array($argv[1], array('--help', '-help', '-h', '-?'))) {
      require (colesoApplication::getConfigVal('/bulldoc/systemTemplates').'help.tpl.phtml');
    } else {
      $key=$argv[1];
      $this->buildBook($key);
    }
  }
}
$old = umask(0);
$builder=new docgenBuilder();
$builder->run();
echo "\n";
umask($old);
?>