<h3><?php echo $title; ?></h3>
&laquo; <a href='<?php echo $backToViewLink; ?>'><?php echo strtolower(colesoApplication::getMessage('form','viewtext')); ?></a>
<form method='post'>
<input name='<?php echo $tokenFieldName; ?>' type='hidden' value='<?php echo $tokenValue; ?>' />
<textarea name='content' style='width: 680px;height: 300px'><?php echo $content; ?></textarea><br/>
<input type='submit' value='<?php echo colesoApplication::getMessage('form','savetext'); ?>'>
&nbsp;
<input type='submit' name='save_view' value='<?php echo colesoApplication::getMessage('bulldoc','save_view'); ?>'>
</form>
