<!-- #item# -->
<p style='margin-top: 5px;margin-bottom: 5px;font-size: x-small;'><a href='<?php echo $key ?>/index.html'><?php echo $title; ?></a></p>
<!-- #separator# -->
<h2 style='color: #666666;font-size: small;margin-top: 30px;margin-bottom: 5px'><?php echo $title; ?></h2>
<!-- #layout# -->
<html>
<head>
</head>
<body>
<div style='width: 900px;background-color: #cdcdcd;padding: 10px;font-weight: bold;font-size: 14px'>BullDoc</div>
<div style='padding-left: 30px'>
<h1 style='color: #666666;font-size: medium'>Доступные книги</h1>
<?php echo $content; ?>
</div>
</body>
</html>
