<table>
<tr>
<td style='vertical-align: top'>
<ul>
<?php if (count($upTitle)): ?>
<?php for($upLevel=count($upTitle)-1;$upLevel>=0;$upLevel--): ?>
<li><a href="<?php echo str_repeat('../',$upLevel).$upLevelLink; ?>"><?php echo $upTitle[$upLevel]; ?></a></li>
<?php endfor; ?>
<?php endif; ?>
</ul>
<ul>
<?php echo $menu; ?>
</ul>
<td>
<td style='padding-left: 20px'>

<table style='width: 100%;margin-bottom: 20px'>
<tr>
<td><?php 
if ($prev) echo "<a href='".$prev['href']."'>&laquo;".$prev['title']."</a>";
else echo '&nbsp;';
?>
</td>
<td style='text-align: right'>
<?php
if ($next) echo "<a href='".$next['href']."'>".$next['title']." &raquo;</a>";
else echo '&nbsp;';
?>
</td>
</tr>
</table>
<?php if ($path!='index.html'):?><h2><?php echo $curTitle; ?></h2><?php endif; ?>
<?php echo $content; ?>
</td></tr>
</table>
