<body style='margin: 10px'>
<div style='margin-left: 40px;margin-right: 40px'>
<h1><?php echo $bookData['title']; ?></h1>
<?php echo $content; ?>
</div>
<div style='margin-top: 40px;width: 100%'>
<hr/>
<p style='color: #ccc'>
<?php if (isset($bookData['copyright'])):?>&copy; <?php echo $bookData['copyright']; ?><br/><?php endif; ?>
<?php if (isset($bookData['site'])):?><a href='http://<?php echo $bookData['site']; ?>'><?php echo $bookData['site']; ?></a><br/><?php endif; ?>
</p>
</div>
</body>
