general_title:
  separatorTitle: BullDoc
  
bulldoc_book:

bulldoc_chm:
  title: BullDoc CHM
  rootIndexLevel: -1
  source: bulldoc_book
  dest: bulldoc_chm
  theme: blueprint
  outputMode: chm

bulldoc_single_page:
  title: BullDoc Single Page
  rootIndexLevel: -1
  source: bulldoc_book
  theme: blueprint
  outputMode: html_single
  hideOnBookShelf: 1

bulldoc_site:
  title: BullDoc for Web-Site
  source: bulldoc_book
  dest: ../../../doc
  theme: blueprint_site
  hideOnBookShelf: 1
  
bulldoc_emptytheme:
  title: Empty theme sample
  source: bulldoc_book
  theme: empty

colseo_title:
  separatorTitle: Компоненты ColESO

coleso_core:
  title: ColESO Core
  source: d:\www\users\coleso\www\lib\coleso\_dev\doc\
  dest: d:\www\users\coleso\www\lib\coleso\_dev\compiled_doc
  theme: blueprint

coleso_forms:
  title: ColESO Forms
  source: d:\www\users\coleso\www\lib\coleso_forms\_dev\doc\
  dest: d:\www\users\coleso\www\lib\coleso_forms\_dev\compiled_doc
  theme: blueprint

storm:
  title: stORM
  source: d:\www\users\coleso\www\lib\storm\_dev\doc\
  dest: d:\www\users\coleso\www\lib\storm\_dev\compiled_doc
  theme: blueprint

newbooks_title:
  separatorTitle: Новые книги
test:
test2:
bulldoc_single: