<!-- #menu_topic# -->
<li><a href='<?php echo $href ?>'><?php echo $title; ?></a></li>
<!-- #active_menu_topic# -->
<li class='active'><?php echo $title ?></li>
<!-- #toc_topic# -->
<div style='margin-top: 7px;margin-left: <?php echo 20*$level; ?>px'><a href='<?php
if ($outputMode=='html_single') echo '#'.$path;
else echo $href; 
?>'><?php echo $title; ?></a></div>
<!-- #toc# -->
<div style='margin-top: 0px;margin-left: 40px'><?php echo $content; ?></div>
