<!-- #item# -->
<?php if (!isset($hideOnBookShelf) || !$hideOnBookShelf):?>
<p style='margin-top: 5px;margin-bottom: 5px;font-size: x-small;'><a href='<?php echo $key ?>/index.html'><?php echo $bookShelfTitle; ?></a></p>
<?php endif; ?>
<!-- #separator# -->
<h2 style='color: #666666;font-size: small;margin-top: 30px;margin-bottom: 5px'><?php echo $title; ?></h2>
<!-- #layout# -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=<?php echo colesoApplication::getConfigVal('/system/lngEncoding');?>">
</head>
<body>
<div style='width: 900px;background-color: #cdcdcd;padding: 10px;font-weight: bold;font-size: 14px'>BullDoc</div>
<div style='padding-left: 30px'>
<h1 style='color: #666666;font-size: medium'>Доступные книги</h1>
<?php echo $content; ?>
</div>
</body>
</html>
