<!-- #indexHeader# -->
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN">
<HTML>
<HEAD>
<meta name="GENERATOR" content="Microsoft&reg; HTML Help Workshop 4.1">
<!-- Sitemap 1.0 -->
</HEAD><BODY>
<UL>
<!-- #indexTopic# -->
	<LI> <OBJECT type="text/sitemap">
		<param name="Name" value="<?php echo $word; ?>">
<?php foreach ($pages as $page): ?>
		<param name="Name" value="<?php echo $page['title']; ?>">
		<param name="Local" value="<?php echo $page['path']; ?>">
<?php endforeach; ?>
		</OBJECT>
<!-- #indexFooter# -->
</UL>
</BODY></HTML>
