<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<link rel="stylesheet" href="<?php echo $assetsURL; ?>blueprint/screen.css" type="text/css" media="screen, projection"/>
<link rel="stylesheet" href="<?php echo $assetsURL; ?>blueprint/print.css" type="text/css" media="print"/>
<link rel="stylesheet" media="screen" type="text/css" href="<?php echo $assetsURL; ?>style.css" />
  <style type='text/css'>
    ul.toc li {
      background-image: url(<?php echo $assetsURL; ?>bullet.gif);
    }
    ul.toc li.up {
      background-image: url(<?php echo $assetsURL; ?>caret_up.gif);
    }
    ul.toc li.home {
      background-image: url(<?php echo $assetsURL; ?>caret_home.gif);
    }
    ul.toc li.active {
      background-image: url(<?php echo $assetsURL; ?>bullet_active.gif);
    }
  
  </style>
  <title><?php echo $bookTitle.' :: '; ?><?php echo $curTitle; ?></title>
</head>
<body>
<div class="container">
<div class="column span-24 first last" style='background-color: #dddddd;margin-bottom: 40px'>
<div class="column span-12 first"><h1><a href='/' style='color: #333333;text-decoration: none'><?php echo $bookTitle; ?></a></h1></div>
<div class="column span-12 last" style='text-align: right;'>
<div style='margin-right: 7px'><a href='/'>главная</a> : <a href='/download.html'>скачать</a> : <a href='/doc/appendix/authors.html'>авторы</a> : <a href='/doc/appendix/license.html'>лицензия</a></div>
</div>
</div>
<div class="column span-4 first" style='width: 140px'>
<ul class='toc'>
<li class='home'><a href="<?php echo $rootURL; ?>">Начало</a></li>
<?php if (count($upTitle)): ?>
<?php for($upLevel=count($upTitle)-1;$upLevel>=0;$upLevel--): ?>
<li class='up'><a href="<?php echo str_repeat('../',$upLevel).$upLevelLink; ?>"><?php echo $upTitle[$upLevel]; ?></a></li>
<?php endfor; ?>
<?php endif; ?>
</ul>
<ul class='toc'>
<?php echo $menu; ?>
</ul>
</div>
<div class="column span-20 last" style='margin-left: 9px;border-left: 1px solid #eee'>
<div class="column span-9 first prepend-1">
<?php 
if ($prev) echo "<a href='".$prev['href']."'>&laquo;".$prev['title']."</a>";
else echo '&nbsp;';
?>
</div>
<div class="column span-9 last append-1" style='text-align: right'>
<?php
if ($next) echo "<a href='".$next['href']."'>".$next['title']." &raquo;</a>";
else echo '&nbsp;';
?>
</div>

<div class='prepend-2 append-1' style='margin-top: 40px;'>
<?php if ($path!='index.html'):?><h2><?php echo $curTitle; ?></h2><?php endif; ?>
<?php echo $content; ?>
</div>
</div>
<div class='column span-24 first last' style='margin-top: 40px'>
<hr/>
<p style='color: #ccc'>
<?php if (isset($bookData['copyright'])):?>&copy; <?php echo $bookData['copyright']; ?><br/><?php endif; ?>
<?php if (isset($bookData['site'])):?><a href='http://<?php echo $bookData['site']; ?>'><?php echo $bookData['site']; ?></a><br/><?php endif; ?>
</p>
</div>

</div>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-3935311-1");
pageTracker._initData();
pageTracker._trackPageview();
</script>
</body>
</html>
