#!/usr/bin/env php
<?php
require_once('bootstrap.php');
require_once(colesoLibrarian::getModule('docgen/output_generator.class.php'));
require_once(colesoLibrarian::getModule('docgen/chm_generator.class.php'));


class docgenBuilder  extends onlineBookLoader
{
  
//---------------------------------------------------
  private function buildBook($key)
  {
    if (!isset($this->books[$key])) {
      $this->createBook($key);
      echo 'New book created';
    } else {
      $render=$this->getBookRenderer($key);
      $render->setMode('static');
      $generator= new outputGenerator($render,$this->getBookDest($key));
      $generator->build();
    }
  }
//---------------------------------------------------
  private function createBook($key)
  {
    $bookDir=colesoApplication::getConfigVal('/docgen/workshopDir')."source/$key/";
    mkdir ($bookDir,0666);
    mkdir ($bookDir.'pages',0666);
    file_put_contents($bookDir.'toc.yml','');
    file_put_contents($bookDir.'book_data.yml',"title: $key\nauthor: Incognito\ncopyright: Me, 2008\nsite: www.mysite.ru");
    
    $bookshelfFile=colesoApplication::getConfigVal('/system/docRoot').'config/bookshelf.yml';
    file_put_contents($bookshelfFile,"\n$key:",FILE_APPEND);
  }
//---------------------------------------------------
  private function buildCHMToc($key)
  {
    $tocFile=$this->getTocFileName($key);
    $chmBuilder=new buildCHMToc($tocFile,$key);
    list($toc,$proj)=$chmBuilder->buildTOC();
    $outputPath=rtrim($this->getBookDest($key),'\\/').'/';
    file_put_contents($outputPath.$key.'.hhc',$toc);
    file_put_contents($outputPath.$key.'.hhp',$proj);
    echo "\nchm structure built\n";
  }
  
//---------------------------------------------------
  public function run()
  {
    global $argc,$argv;
    if ($argc != 2 || in_array($argv[1], array('--help', '-help', '-h', '-?'))) {
      require (colesoApplication::getConfigVal('/docgen/systemTemplates').'help.tpl.phtml');
    } else {
      $key=$argv[1];
      $this->buildBook($key);
      if ($this->needChm($key)) $this->buildCHMToc($key);
    }
  }
}

$builder=new docgenBuilder();
$builder->run();
?>