general_title:
  separatorTitle: Основной раздел
  
bulldoc_book:

bulldoc_chm:
  title: BullDoc CHM
  rootIndexLevel: -1
  source: bulldoc_book
  dest: bulldoc_chm
  theme: blueprint_chm
  buildChm: 1

bulldoc_single_page:
  title: BullDoc Single Page
  rootIndexLevel: -1
  source: bulldoc_book
  theme: blue_print_single
  singlePageExport: 1
  hideOnBookShelf: 1

bulldoc_site:
  title: BullDoc for Web-Site
  source: bulldoc_book
  dest: ../../../doc
  theme: blueprint_site
  hideOnBookShelf: 1
  
bulldoc_emptytheme:
  title: Empty theme sample
  source: bulldoc_book
  theme: empty

newbooks_title:
  separatorTitle: Новые книги